---
title: Stoom
timezone: UTC
collections:
  agenda:
    title: Agenda
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Nerdlab
description: Wat als kunst en technologie samenkomen? Een vraag waar we bij Nerdlab
  vaak over nadenken, en waar we jou voor nodig hebben!
footer:
  project: Volg de progressie van het Stoom project
  project-url: http://nerdlab.be/
  author: Nerdlab
  author-url: http://nerdlab.be/
  facebook-url: https://www.facebook.com/Nerdlab
  twitter-url: https://twitter.com/NerdLab9000
  instagram-url: https://www.instagram.com/nerdlab9000/
  partners:
  - title: Vlaamse overheid
    img: 
    url: http://www.vlaanderen.be/nl
  - title: Fisheye
    img: 
    url: http://fisheye.eu/
permalink: pretty
exclude:
- _site
- scss
- "*scss"
- Gem*
- Guard*
- "*rb"
- ".sass-cache"
- ".git*"
- config.rb
- README.md
- LICENSE.md
- CONTRIBUTING.md
- "*.json"
- docroot
- node_modules
- gulpfile.js
- install.sh
- lint.yml
